### PR TITLE
Add MPI variants

### PR DESCRIPTION
**Pull request by ChristopherHogan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ChristopherHogan** [comment]
@minrk, thanks for your work on MPI variants. I'm trying it out here. Does everything look correct?

**Comment by minrk** [comment]
> Does everything look correct?

I believe so!

**Comment by minrk** [comment]
Ah, while the metadata update looks right, does build.sh also need updating to set the flag? It's probably worth adding specific tests to verify that the mpi builds work right.

**Comment by ChristopherHogan** [comment]
Of course! Thanks for catching that. I see in `hdf5-feedstock` that the `mpi` variable is available in `build.sh`. How is that accomplished? Does setting `mpi` in `meta.yaml` via jinja automatically make `mpi` available in `build.sh`?

**Comment by minrk** [comment]
All the variables in conda_build_config.yaml show up as environment variables in build.sh.

**Pull request merged**
